src/apps/main/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^login/$', views.login, name='login'),
]

src/generate_adverts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'^v2/', include('apps.adverts_v2.urls', namespace='adverts_v2')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/apps/main/models.py
from django.db import models

# Create your models here.

src/apps/main/forms.py
from django.contrib.auth.forms import AuthenticationForm


class CustomAuthenticationForm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs.update({'class': 'form-control'})

src/apps/main/views.py
from django.contrib.auth.views import login as django_login, auth_logout
from django.http import Http404
from django.shortcuts import redirect

from apps.adverts_v2.models import Category
from apps.main.forms import CustomAuthenticationForm


def login(request):
    if request.user.is_authenticated():
        return redirect('main:index')
    return django_login(request, template_name='main/login.html', authentication_form=CustomAuthenticationForm)


def logout(request):
    auth_logout(request)
    return redirect('main:index')


def index(request):
    first_category = Category.objects.first()
    if first_category is None:
        raise Http404
    return redirect('adverts_v2:new-adverts', first_category.alias)

src/apps/main/templates/main/index.html
{% extends 'base.html' %}

{% block content %}
    {{ message }}
{% endblock %}

src/apps/main/templates/main/login.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
            <div id="registration-form-wrapper" class="well">
                {% if form.errors %}
                    <div class="alert alert-danger">
                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                                {{ error }}{% if not forloop.last %}<br>{% endif %}
                            {% endfor %}
                        {% else %}
                            Обнаружены ошибки в полях формы. Исправьте их и попробуйте снова.
                        {% endif %}
                    </div>
                {% endif %}
                <form method="POST" action='{% url 'main:login' %}'>
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group{% if field.errors %} has-error{% endif %}">
                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                            {{ field }}
                            {% if field.errors %}
                                <p class="help-block">
                                    {% for error in field.errors %}
                                        {{ error }}{% if not forloop.last %}<br>{% endif %}
                                    {% endfor %}
                                </p>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-default">Войти</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}