src/apps/adverts_v2/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(
        r'^(?P<category>[\w-]+)/new-adverts/$',
        views.NewAdvertsList.as_view(),
        name='new-adverts'
    ),
    url(
        r'^(?P<category>[\w-]+)/used-adverts/$',
        views.UsedAdvertsList.as_view(),
        name='used-adverts'
    ),
    url(
        r'^(?P<category>[\w-]+)/rejected-adverts/$',
        views.RejectedAdvertsList.as_view(),
        name='rejected-adverts'
    ),
    url(
        r'^(?P<category>[\w-]+)/adverts-in-work/$',
        views.AdvertsInWork.as_view(),
        name='adverts-in-work'
    ),
    url(
        r'^(?P<category>[\w-]+)/get-package/$',
        views.get_package,
        name='get-package'
    ),
    url(
        r'^(?P<category>[\w-]+)/bulk-create/$',
        views.AdvertsBulkCreate.as_view(),
        name='bulk-create'
    ),
    url(
        r'^(?P<category>[\w-]+)/work-complete/$',
        views.work_complete,
        name='work-complete'
    ),
    url(
        r'^change-photo-status/(?P<photo_id>\d+)/$',
        views.change_photo_status,
        name='change-photo-status'
    ),
    url(
        r'^refresh-description/(?P<advert_id>\d+)/$',
        views.refresh_description,
        name='refresh-description'
    ),
    url(
        r'^set-original-description/(?P<advert_id>\d+)/$',
        views.set_original_description,
        name='set-original-description'
    ),
    url(
        r'^change-advert-status/(?P<advert_id>\d+)/$',
        views.change_advert_status,
        name='change-advert-status'
    ),
    url(
        r'^change-advert/(?P<advert_id>\d+)/$',
        views.AdvertChange.as_view(),
        name='change-advert'
    ),
]

src/generate_adverts/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'', include('apps.main.urls', namespace='main')),
    url(r'^v2/', include('apps.adverts_v2.urls', namespace='adverts_v2')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

src/apps/adverts_v2/forms.py
from django import forms
from form_utils.forms import BetterModelForm


class CountForm(forms.Form):
    count = forms.IntegerField(
        label='Количество объявлений',
        max_value=100,
        min_value=1,
        initial=10,
        widget=forms.NumberInput(attrs={'class': 'form-control'})
    )


class BaseAdvertForm(BetterModelForm):
    class Meta:
        exclude = ('id', 'category', 'donor', 'donor_url', 'status', 'visible')
        widgets = {
            'title': forms.TextInput,
            'description_original': forms.Textarea(attrs={'readonly': 'readonly'}),
            'title_original': forms.TextInput(attrs={'readonly': 'readonly'})
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for field in self.fields.values():
            if isinstance(field.widget, (forms.TextInput, forms.Textarea, forms.Select)):
                field.widget.attrs.update({'class': 'form-control'})
            elif isinstance(field.widget, forms.CheckboxInput):
                field.is_checkbox = True


FIELDSETS = {
    'default': (
        ('address', {
            'legend': 'Адрес',
            'fields': ('city', 'district', 'metro')
        }),
        ('common', {
            'legend': 'Основные данные',
            'fields': ('title_original', 'title', 'description_original', 'description', 'price')
        })
    ),
    'apartmentadvert': (
        ('address', {
            'legend': 'Адрес',
            'fields': ('city', 'district', 'metro', 'street', 'house_number')
        }),
        ('common', {
            'legend': 'Основные данные',
            'fields': ('title_original', 'title', 'description_original', 'description', 'price', 'rooms_number',
                       'floor', 'floors_total', 'area_living', 'area_total', 'area_kitchen', 'ceiling_height',
                       'beds_number', 'condition', 'apartment_type')
        }),
        ('address', {
            'legend': 'Удобства',
            'fields': ('has_furniture', 'has_kitchen', 'has_refrigerator', 'has_washing_machine',
                       'has_conditioner', 'has_tv', 'has_internet')
        }),
    ),
    'cottageadvert': (
        ('address', {
            'legend': 'Адрес',
            'fields': ('city', 'district', 'metro')
        }),
        ('common', {
            'legend': 'Основные данные',
            'fields': ('title_original', 'title', 'description_original', 'description', 'price', 'area_house',
                       'area_homestead', 'floors_house', 'wall_material')
        })
    )
}


def _get_fieldsets(model_name):
    return FIELDSETS.get(model_name) or FIELDSETS['default']


def modelform_fabric(model):
    meta = type('Meta', (BaseAdvertForm.Meta, ), {'model': model, 'fieldsets': _get_fieldsets(model._meta.model_name)})
    return type('AdvertChangeForm', (BaseAdvertForm, ), {'Meta': meta})

src/apps/adverts_v2/views.py
import os
import uuid

from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.db import transaction
from django.http import JsonResponse, HttpResponse
from django.shortcuts import get_object_or_404
from django.template.loader import render_to_string
from django.utils.decorators import method_decorator
from django.views.decorators.http import require_GET
from django.views.generic import View
from django.views.generic.base import TemplateResponseMixin

from apps.adverts_v2.forms import CountForm
from apps.adverts_v2.models import Category, Advert, AdvertPhoto, AdvertInWork
from libs.decorators import ajax_required
from libs.utils import ChoicesHelper, import_by_name
from . import options


def get_statuses_counts(request, category):
    statuses_counts = {}
    queryset = Advert.objects.get_category_queryset(category_alias=category.alias)
    for val, _ in options.ADVERT_STATUSES:
        if val == options.IN_WORK:
            count = queryset.visible().filter(advertinwork__user=request.user).count()
        else:
            count = queryset.available().filter(status=val).count()
        statuses_counts[val] = count
    return statuses_counts


class AdvertsList(View, TemplateResponseMixin):
    template_name = 'adverts_v2/adverts.html'
    status = None
    category = None

    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(Category, alias=kwargs.pop('category'))
        return super().dispatch(request, *args, **kwargs)

    def get_adverts_queryset(self):
        return self.category.get_adverts_queryset().get_by_status(user=self.request.user, status=self.status).visible()

    def get_paginated_adverts(self):
        paginator = Paginator(self.get_adverts_queryset(), options.ADVERTS_ON_PAGE)
        paginator_page = self.request.GET.get('page', 1)
        try:
            return paginator.page(paginator_page)
        except PageNotAnInteger:
            return paginator.page(1)
        except EmptyPage:
            return paginator.page(paginator.num_pages)

    def render_adverts_list(self):
        return render_to_string('adverts_v2/adverts-list.html', {
            'paginated_adverts': self.get_paginated_adverts(),
            'statuses': options.ADVERT_STATUSES_FULL,
            'status': self.status,
            'current_category': self.category,
        })

    def get(self, request):
        context = {
            'rendered_adverts_list': self.render_adverts_list(),
        }

        if request.is_ajax():
            return JsonResponse(context)

        def build_info(value, title, extra):
            return value, title, extra, self.category.get_adverts_queryset().get_by_status(request.user, value).count()

        context.update(
            current_category=self.category,
            categories=Category.objects.all(),
            status=self.status,
            statuses=[build_info(value, title, extra) for value, title, extra in options.ADVERT_STATUSES_FULL]
        )
        return self.render_to_response(context)


class NewAdvertsList(AdvertsList):
    status = options.NEW


class RejectedAdvertsList(AdvertsList):
    status = options.REJECTED


class UsedAdvertsList(AdvertsList):
    status = options.USED


class AdvertsInWork(AdvertsList):
    status = options.IN_WORK


class AdvertChange(View, TemplateResponseMixin):
    template_name = 'adverts_v2/advert-form.html'

    @method_decorator(ajax_required)
    def dispatch(self, request, *args, **kwargs):
        advert = get_object_or_404(Advert, id=kwargs.pop('advert_id'))
        can_edit, error = advert.can_edit(request.user)
        if not can_edit:
            return JsonResponse({
                'error': 'Редактирование объявления запрещено. {0}'.format(error)
            })

        kwargs.update(advert=advert)
        return super().dispatch(request, *args, **kwargs)

    def get(self, request, advert):
        form_class = advert.get_change_form_class()
        return self.render_to_response({
            'form': form_class(instance=advert)
        })

    def post(self, request, advert):
        form_class = advert.get_change_form_class()
        form = form_class(instance=advert, data=request.POST)
        if form.is_valid():
            if not form.has_changed():
                return JsonResponse({
                    'not_changed': True
                })

            advert = form.save()
            return JsonResponse({
                'updated_advert': render_to_string('adverts_v2/advert-in-list.html', {
                    'advert': advert,
                    'status': advert.status,
                    'statuses': options.ADVERT_STATUSES_FULL,
                })
            })

        form_errors = {}
        for key, value in form.errors.items():
            form_errors.setdefault(key, []).append(value)
        print(form_errors)
        return JsonResponse({
            'form_errors': form_errors
        })


class AdvertsBulkCreate(View, TemplateResponseMixin):
    template_name = 'adverts_v2/advert-bulk-create-form.html'
    category = None
    form_class = None

    @method_decorator(ajax_required)
    def dispatch(self, request, *args, **kwargs):
        self.category = get_object_or_404(Category, alias=kwargs.pop('category'))
        self.form_class = self.category.get_change_form_class()
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        return self.render_to_response({
            'form_count': CountForm(),
            'form': self.form_class()
        })

    def post(self, request):
        form_count = CountForm(request.POST)
        if not form_count.is_valid():
            form_errors = {}
            for key, value in form_count.errors.items():
                form_errors.setdefault(key, []).append(value)
            return JsonResponse({
                'form_errors': form_errors
            })

        form = self.form_class(request.POST)
        if form.is_valid():
            for _ in range(0, form_count.cleaned_data['count']):
                form._meta.model.objects.create(
                    donor=options.DUMMY,
                    donor_url=options.DUMMY_URL.format(uuid.uuid4()),
                    category=self.category,
                    **form.cleaned_data
                )

            return JsonResponse({
                    'link': reverse('adverts_v2:new-adverts', args=(self.category.alias, ))
                })

        form_errors = {}
        for key, value in form.errors.items():
            form_errors.setdefault(key, []).append(value)
        return JsonResponse({
            'form_errors': form_errors
        })


@require_GET
@ajax_required
def work_complete(request, category):
    with transaction.atomic():
        adverts = Advert.objects.get_category_queryset(category).filter(advertinwork__user=request.user)
        adverts.update(status=options.USED)
        AdvertInWork.objects.filter(advert__in=adverts).delete()
    return JsonResponse({
        'redirect': reverse('adverts_v2:new-adverts', args=(category, ))
    })


@require_GET
@ajax_required
def add_to_work(request, advert_id):
    advert = get_object_or_404(Advert, id=advert_id)
    can_edit, error = advert.can_edit(request.user)
    if not can_edit:
        return JsonResponse({
            'error': 'Не удалось добавить объявление в работу. {0}'.format(error)
        })

    AdvertInWork.objects.get_or_create(advert=advert, user=request.user)
    return JsonResponse({
        'items': get_statuses_counts(request, advert.category)
    })


@require_GET
@ajax_required
def change_photo_status(request, photo_id):
    image = get_object_or_404(AdvertPhoto, id=photo_id)
    can_edit, error = image.can_edit(request.user)
    if not can_edit:
        return JsonResponse({
            'error': 'Не удалось изменить статус фото. {0}'.format(error)
        })

    status = request.GET.get('status')
    if status and status.lower() in ('false', 'true'):
        status = True if status == 'true' else False
        if image.enabled != status:
            image.enabled = status
            image.save(update_fields=('enabled',))
    return JsonResponse({})


@require_GET
@ajax_required
def refresh_description(request, advert_id):
    advert = get_object_or_404(Advert, id=advert_id)
    can_edit, error = advert.can_edit(request.user)
    if not can_edit:
        return JsonResponse({
            'error': 'Не удалось обновить описание. {0}'.format(error)
        })

    advert.generate_texts(fields=('description', ))
    advert.save(update_fields=('description', ))
    return JsonResponse({'text': advert.description})


@require_GET
@ajax_required
def set_original_description(request, advert_id):
    advert = get_object_or_404(Advert, id=advert_id)
    can_edit, error = advert.can_edit(request.user)
    if not can_edit:
        return JsonResponse({
            'error': 'Не удалось обновить объявление. {0}'.format(error)
        })

    target_field = request.GET.get('field')
    if target_field not in options.AUTO_GENERATED_FIELDS:
        return JsonResponse({
            'error': 'Некорректное поле {}'.format(target_field)
        })

    setattr(advert, target_field, getattr(advert, '{}_original'.format(target_field)))
    advert.save(update_fields=(target_field, ))

    return JsonResponse({
        'updated_advert': render_to_string('adverts_v2/advert-in-list.html', {
            'advert': advert,
            'status': advert.status,
            'statuses': options.ADVERT_STATUSES_FULL,
        })
    })


@require_GET
@ajax_required
def change_advert_status(request, advert_id):
    advert = get_object_or_404(Advert, id=advert_id)
    can_edit, error = advert.can_edit(request.user)
    if not can_edit:
        return JsonResponse({
            'error': 'Не удалось сменить статус объявления. {0}'.format(error)
        })

    status = request.GET.get('status')
    try:

src/apps/adverts_v2/templates/adverts_v2/advert-bulk-create-form.html
<form method="post">
    {% csrf_token %}

    <fieldset>
        <label for="{{ form_count.count.id_for_label }}">{{ form_count.count.label }}</label>
        {{ form_count.count }}
        <span class="help-block error-text"></span>
    </fieldset>

    {% for fieldset in form.fieldsets %}
        <fieldset>
            {% for field in fieldset %}
                <div class="form-group">
                    {% if field.field.is_checkbox %}
                        <div class="checkbox">
                            <label>
                                {{ field }} {{ field.label }} <span class="error-text"></span>
                            </label>
                        </div>
                    {% else %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="help-block error-text"></span>
                    {% endif %}
                </div>
            {% endfor %}
        </fieldset>
    {% endfor %}
</form>

src/apps/adverts_v2/templates/adverts_v2/advert-form.html
<form method="post">
    {% csrf_token %}
    {% for fieldset in form.fieldsets %}
        <fieldset>
            {% for field in fieldset %}
                <div class="form-group">
                    {% if field.field.is_checkbox %}
                        <div class="checkbox">
                            <label>
                                {{ field }} {{ field.label }} <span class="error-text"></span>
                            </label>
                        </div>
                    {% else %}
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <span class="help-block error-text"></span>
                    {% endif %}
                </div>
            {% endfor %}
        </fieldset>
    {% endfor %}
</form>

src/apps/adverts_v2/templates/adverts_v2/advert-in-list.html
<div id="advert-{{ advert.id }}" class="row advert-item">
    {% with photos=advert.photos.all %}
        <div class="col-xs-12">
            <div class="row">
                <div class="col-xs-12">
                    <div class="row advert-item-header">
                        <div class="col-xs-3 advert-id">
                            <h2># {{ advert.id }}</h2>
                        </div>
                        <div class="col-xs-9 advert-controls" data-advert-id="{{ advert.id }}">
                            <button type="button" class="btn btn-default advert-renew-desc">Обновить описание</button>
                            <button type="button" class="btn btn-default advert-edit">Редактировать</button>

                            <div class="btn-group" role="group" aria-label="...">
                                <div class="btn-group" role="group">
                                    <button type="button" class="btn btn-default dropdown-toggle"
                                            data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        переместить
                                        <span class="caret"></span>
                                    </button>
                                    <ul class="dropdown-menu">
                                        {% for value, title, extra in statuses %}
                                            <li{% if value == status %} class="disabled"{% endif %}>
                                                <a class="advert-status-change" data-status-id="{{ value }}">
                                                    {{ extra.button_name }}</a>
                                            </li>
                                        {% endfor %}
                                    </ul>
                                </div>
                            </div>

                            {% if status != 1 %}
                                <button type="button" class="btn btn-danger advert-reject">Отклонить</button>
                            {% endif %}

                            {% if status != 3 %}
                                <button type="button" class="btn btn-success advert-add-to-work">В работу</button>
                            {% endif %}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-8">
                            <div class="row">
                                <div class="col-xs-12">
                                    {% if advert.title_original and advert.title_original != advert.title %}
                                        <h5><i>{{ advert.title_original }}</i></h5>
                                        <p><button type="button" class="btn btn-default set-original" data-field="title">
                                            Использовать оригинальный заголовок</button></p>
                                    {% endif %}

                                    {% if advert.title %}
                                        <h4>{{ advert.title }}</h4>
                                    {% else %}
                                        <div class="alert alert-warning" role="alert">Не заполнен заголовок</div>
                                    {% endif %}

                                    {% if advert.description_original and advert.description_original != advert.description %}
                                        <div class="well well-sm advert-original-description">
                                            <i>{{ advert.description_original|linebreaksbr }}</i>
                                        </div>
                                        <p><button type="button" class="btn btn-default set-original" data-field="description">
                                            Использовать оригинальное описание</button></p>
                                    {% endif %}

                                    {% if not advert.description %}
                                        <div class="alert alert-warning" role="alert">Не заполнено описание</div>
                                    {% endif %}

                                    <div class="well well-sm advert-description">
                                        {{ advert.description|linebreaksbr }}
                                    </div>

                                </div>
                                {% if photos %}
                                    <div class="col-xs-12 advert-photos">
                                        {% for photo in photos %}
                                            <div class="col-xs-3 advert-photo-wrapper">
                                                <div class="advert-photo-controls" data-photo-id="{{ photo.id }}">
                                                    <input title="статус фотографии" type="checkbox"
                                                            {% if photo.enabled %} checked{% endif %}>
                                                </div>
                                                <a href="{{ photo.image.url }}">
                                                    <img src="{{ photo.image.small.url }}" class="img-thumbnail">
                                                </a>
                                            </div>
                                            {% if forloop.counter|divisibleby:4 %}
                                                </div>
                                                <div class="col-xs-12 advert-photos">
                                            {% endif %}
                                        {% endfor %}
                                        </div>
                                {% endif %}
                            </div>
                        </div>
                        <div class="col-xs-4">
                            <ul class="list-unstyled">
                                {% for title, value in advert.short_stats_items_generator %}
                                    <li><b>{{ title }}</b>: {{ value }}</li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    {% endwith %}
</div>

src/apps/adverts_v2/templates/adverts_v2/adverts-list.html
{% for advert in paginated_adverts %}
    {% include 'adverts_v2/advert-in-list.html' %}
{% endfor %}

{% if paginated_adverts.has_next %}
    <div class="row">
        <div class="col-xs-6 col-xs-offset-3">
            <a id="load-more-button" class="btn btn-primary btn-lg btn-block" href="?page={{ paginated_adverts.next_page_number }}" role="button">Показать еще</a>
        </div>
    </div>
{% endif %}

src/apps/adverts_v2/templates/adverts_v2/adverts.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block extra_head %}
    <link href="{% static 'css/magnific-popup.css' %}" rel="stylesheet">
{% endblock %}

{% block extra_js %}
    <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'smart-selects/admin/js/chainedfk.js' %}"></script>
    <script src="{% static 'adverts_v2/js/adverts-list.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="row" id="adverts-wrapper">
        <div class="col-xs-3">
            <div id="adverts-left-menu">
                <ul class="nav nav-pills nav-stacked">
                    {% for value, title, extra, count in statuses %}
                        <li id="menu-status-{{ value }}" data-status-id="{{ value }}"
                            role="presentation"{% if value == status %} class="active"{% endif %}>
                            <a href="{% url extra.url_name current_category.alias %}">{{ extra.name_plural }} <span
                                    class="badge">{{ count }}</span></a>
                        </li>
                    {% endfor %}
                </ul>
                {% if status == 0 %}
                    <a id="bulk-create" role="button" href="{% url 'adverts_v2:bulk-create' current_category.alias %}"
                       class="btn btn-block btn-default">Массовое создание</a>
                {% endif %}
                {% if status == 3 %}
                    <a id="work-complete" role="button" href="{% url 'adverts_v2:work-complete' current_category.alias %}"
                       class="btn btn-block btn-default">Завершить работу</a>
                    <a role="button" href="{% url 'adverts_v2:get-package' current_category.alias %}" class="btn btn-block btn-default"
                       target="_blank">Скачать архив</a>
                {% endif %}
            </div>
        </div>
        <div class="col-xs-9">
            <div class="row">
                <div class="col-xs-12" id="adverts-categories-menu">
                    <nav class="navbar navbar-default">
                        <div class="container-fluid">
                            <div class="navbar-header">
                                {% for category in categories %}
                                    <a role="button"
                                       class="btn btn-default navbar-btn {% if current_category == category %} active{% endif %}"
                                       href="{% url 'adverts_v2:new-adverts' category.alias %}">{{ category.title }}</a>
                                {% endfor %}
                            </div>
                        </div>
                    </nav>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12" id="adverts-list">
                    {{ rendered_adverts_list }}
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="advert-form-modal" tabindex="-1" role="dialog" aria-labelledby="advert-form-modal">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Редактирование объявления #<span class="advert-identifer"></span></h4>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <div class="message-box"></div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary advert-save">Сохранить</button>
                    <button type="button" class="btn btn-primary advert-save-and-close">Сохранить и закрыть</button>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade" id="adverts-bulk-create" tabindex="-1" role="dialog" aria-labelledby="adverts-bulk-create">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Массовое создание объявлений</h4>
                </div>
                <div class="modal-body"></div>
                <div class="modal-footer">
                    <div class="message-box"></div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Закрыть</button>
                    <button type="button" class="btn btn-primary adverts-create">Создать</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}